// Please do not edit this file as it is usd to bootstrap closure dependencies
// when run in source mode (uncompiled)

if (typeof COMPILED == 'undefined') {
  CLOSURE_BASE_PATH = '../../../../library/closure/goog/';
  importScripts(CLOSURE_BASE_PATH + 'bootstrap/webworkers.js',
                CLOSURE_BASE_PATH + 'base.js', CLOSURE_BASE_PATH + 'deps.js',
                CLOSURE_BASE_PATH + '../../../apps/pstj/deps.js',
                '../../build/deps.js', 'main.js');
}
